@echo off
REM This is an emergency fix script for Android Studio and Gradle issues

echo Starting emergency fix for Android Studio and Gradle...
echo.

REM Set and permanently save environment variables
SETX ANDROID_SDK_ROOT "C:\Users\Welsh Pawn\Desktop\AndroidSDK"
SETX ANDROID_HOME "C:\Users\Welsh Pawn\Desktop\AndroidSDK" 
SETX GRADLE_USER_HOME "C:\Users\Welsh Pawn\.gradle"

REM Also set them for the current session
SET ANDROID_SDK_ROOT=C:\Users\Welsh Pawn\Desktop\AndroidSDK
SET ANDROID_HOME=C:\Users\Welsh Pawn\Desktop\AndroidSDK
SET GRADLE_USER_HOME=C:\Users\Welsh Pawn\.gradle

REM Create directories if they don't exist
if not exist "C:\Users\Welsh Pawn\.gradle" mkdir "C:\Users\Welsh Pawn\.gradle"
if not exist "C:\Users\Welsh Pawn\.android" mkdir "C:\Users\Welsh Pawn\.android"

REM Clean Android Studio caches
echo Cleaning Android Studio caches...
if exist "C:\Users\Welsh Pawn\.AndroidStudio*" rmdir /s /q "C:\Users\Welsh Pawn\.AndroidStudio*"
if exist "C:\Users\Welsh Pawn\.android\cache" rmdir /s /q "C:\Users\Welsh Pawn\.android\cache"

REM Clean project caches
echo Cleaning project caches...
if exist "C:\Users\Welsh Pawn\Desktop\UberHelpMain\.gradle" rmdir /s /q "C:\Users\Welsh Pawn\Desktop\UberHelpMain\.gradle"
if exist "C:\Users\Welsh Pawn\Desktop\UberHelpMain\.idea" rmdir /s /q "C:\Users\Welsh Pawn\Desktop\UberHelpMain\.idea"
if exist "C:\Users\Welsh Pawn\Desktop\UberHelpMain\build" rmdir /s /q "C:\Users\Welsh Pawn\Desktop\UberHelpMain\build"
if exist "C:\Users\Welsh Pawn\Desktop\UberHelpMain\app\build" rmdir /s /q "C:\Users\Welsh Pawn\Desktop\UberHelpMain\app\build"

REM Create a freshly updated local.properties file
echo Creating fresh local.properties file...
echo # This file is automatically generated by Android Studio. > "C:\Users\Welsh Pawn\Desktop\UberHelpMain\local.properties"
echo # Do not modify this file -- YOUR CHANGES WILL BE ERASED! >> "C:\Users\Welsh Pawn\Desktop\UberHelpMain\local.properties"
echo # >> "C:\Users\Welsh Pawn\Desktop\UberHelpMain\local.properties"
echo # This file should *NOT* be checked into Version Control Systems, >> "C:\Users\Welsh Pawn\Desktop\UberHelpMain\local.properties"
echo # as it contains information specific to your local configuration. >> "C:\Users\Welsh Pawn\Desktop\UberHelpMain\local.properties"
echo # >> "C:\Users\Welsh Pawn\Desktop\UberHelpMain\local.properties"
echo # Location of the SDK. This is only used by Gradle. >> "C:\Users\Welsh Pawn\Desktop\UberHelpMain\local.properties"
echo sdk.dir=C:\\Users\\Welsh Pawn\\Desktop\\AndroidSDK >> "C:\Users\Welsh Pawn\Desktop\UberHelpMain\local.properties"

REM Create a known-good gradle.properties in user home
echo Creating gradle.properties in user home...
echo org.gradle.daemon=true > "C:\Users\Welsh Pawn\.gradle\gradle.properties"
echo org.gradle.parallel=true >> "C:\Users\Welsh Pawn\.gradle\gradle.properties"
echo org.gradle.configureondemand=true >> "C:\Users\Welsh Pawn\.gradle\gradle.properties"
echo org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 >> "C:\Users\Welsh Pawn\.gradle\gradle.properties"
echo android.useAndroidX=true >> "C:\Users\Welsh Pawn\.gradle\gradle.properties"
echo android.enableJetifier=true >> "C:\Users\Welsh Pawn\.gradle\gradle.properties"

REM Create a dummy gradle-wrapper.properties file
echo Creating gradle-wrapper.properties...
if not exist "C:\Users\Welsh Pawn\Desktop\UberHelpMain\gradle\wrapper" mkdir "C:\Users\Welsh Pawn\Desktop\UberHelpMain\gradle\wrapper"
echo distributionBase=GRADLE_USER_HOME > "C:\Users\Welsh Pawn\Desktop\UberHelpMain\gradle\wrapper\gradle-wrapper.properties"
echo distributionPath=wrapper/dists >> "C:\Users\Welsh Pawn\Desktop\UberHelpMain\gradle\wrapper\gradle-wrapper.properties"
echo distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip >> "C:\Users\Welsh Pawn\Desktop\UberHelpMain\gradle\wrapper\gradle-wrapper.properties"
echo zipStoreBase=GRADLE_USER_HOME >> "C:\Users\Welsh Pawn\Desktop\UberHelpMain\gradle\wrapper\gradle-wrapper.properties"
echo zipStorePath=wrapper/dists >> "C:\Users\Welsh Pawn\Desktop\UberHelpMain\gradle\wrapper\gradle-wrapper.properties"

echo.
echo Emergency fix complete! Please follow these steps:
echo 1. Download Android Studio again from https://developer.android.com/studio
echo 2. Install Android Studio to a simple path like C:\AndroidStudio
echo 3. During setup, let it install the Android SDK to the default location
echo 4. After installation, open Android Studio and create a new empty project to test
echo 5. Only after Android Studio and SDK are working correctly, open this project
echo.
echo Press any key to open the Android Studio download page...
pause > nul

start "" "https://developer.android.com/studio" 